### ISSUE TITLE
[TODO] Upgrade to newer versions of Bot API

### ISSUE THREAD

**Issue by AntonBoch1244** [AntonBoch1244/JavaTelegramBotView#1]
This not an issue.
====

Since last commit, Telegram made a lot of changes.
So this backlog for project. No promises for doing all of this in short period of time.
----

 - [ ] Refresh code.
   - [ ] Implement a newer DTOs.
   - [ ] Upgrade existing DTOs.
   - [ ] Logging.
 - [ ] Make UI changes.
   - [ ] Redesign UI.
   - [ ] Implement tabbed frames.
   - [ ] WebUI.
 - [ ] Implement console/debug CLI.
 - [ ] Implement network subsystem.

After update
----

Drop notice to existing forks about needs to be updated.

You have a pull request and bug report? Feel free to create new a one.
